sudo: required

services:
  - docker

language: java
dist: trusty

branches:
  only:
  - master

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package -U
  - docker build -t jkatanec/katalog_profilov .

after_success:
  - docker login -u="jkatanec" -p="geslo123"
  - docker push jkatanec/katalog_profilov
