version: "2"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=profil
    ports:
      - "5432:5432"
  profil-service:
    image: profil-api:1.00
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://192.168.99.100:5432/profil
    ports:
      - "8080:8080"
    depends_on:
      - postgres