kumuluzee:
  name: katalog_profilov-service
  env:
    name: dev
  version: 1.0.0

  config:
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
      etcd:
        hosts: http://192.168.99.100:2379

  server:
    base-url: http://192.168.99.100:8080
    http:
      port: 8080

  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15

  datasources:
    - jndi-name: jdbc/KatalogProfilovDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/profil
      username: postgres
      password: postgres
      max-pool-size: 20

  rest-properties:
    external-dependencies:
      order-service:
        enabled: true